class TaskError(Exception):
    ...

class InvalidPriorityError(TaskError):
    ...

class InvalidDescriptionError(TaskError):
    ...

class InvalidStatusError(TaskError):
    ...

class InvalidTaskTypeError(TaskError):
    ...

class InvalidPayloadError(TaskError):
    ...

class TaskCreateError(TaskError):
    ...
